In [32]:
import pandas as pd
import sys 
sys.path.append('../src')
from clean import format_time

In [33]:
df = pd.read_csv('../data/raw/flights.csv')

In [34]:
df['name'] = df['name'].str.capitalize().str.strip()
df['name'].unique().tolist()

['United air lines inc.',
 'American airlines inc.',
 'Jetblue airways',
 'Delta air lines inc.',
 'Expressjet airlines inc.',
 'Envoy air',
 'Us airways inc.',
 'Southwest airlines co.',
 'Virgin america',
 'Airtran airways corporation',
 'Alaska airlines inc.',
 'Endeavor air inc.',
 'Frontier airlines inc.',
 'Hawaiian airlines inc.',
 'Mesa airlines inc.',
 'Skywest airlines inc.']

In [35]:
df['name'] = df['name'].str.replace(r'\bco\.?\b','',regex= True)
df['name'] = df['name'].str.replace(r'\binc\.?\b', '', regex=True)
df['name'] = df['name'].str.replace(r'\bcorporation\.?\b','',regex=True)
df['name'] = df['name'].str.replace(r'\.$', '', regex=True)
df['name'] = df['name'].str.replace(r'air\s+lines', 'airlines', regex=True)
df['name'] = df['name'].str.replace(r'\bair\b','airlines',regex=True)
df['name'] = df['name'].replace('Virgin america', 'virgin america airlines')
df['name'] = df['name'].str.strip()
df['name'].unique().tolist()

['United airlines',
 'American airlines',
 'Jetblue airways',
 'Delta airlines',
 'Expressjet airlines',
 'Envoy airlines',
 'Us airways',
 'Southwest airlines',
 'virgin america airlines',
 'Airtran airways',
 'Alaska airlines',
 'Endeavor airlines',
 'Frontier airlines',
 'Hawaiian airlines',
 'Mesa airlines',
 'Skywest airlines']

In [36]:
df['is_cancalled'] = df['dep_time'].isna().astype(int)

In [37]:
df['dep_time_format'] = df['dep_time'].apply(format_time)
df[["dep_time_format","dep_time"]].head()

  dep_time_format  dep_time
0           05:17     517.0
1           05:33     533.0
2           05:42     542.0
3           05:44     544.0
4           05:54     554.0

In [38]:
df['arr_time_format'] = df['arr_time'].apply(format_time)

In [39]:
df['sched_arr_time_formatted']= df['sched_arr_time'].apply(format_time)

In [40]:
df['sched_dep_time_formatted'] = df['sched_dep_time'].apply(format_time)

In [41]:
df['flight_date'] = pd.to_datetime(df[['year','month','day','hour', 'minute']])
df

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,hour,minute,time_hour,name,is_cancalled,dep_time_format,arr_time_format,sched_arr_time_formatted,sched_dep_time_formatted,flight_date
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,5,15,2013-01-01 05:00:00,United airlines,0,05:17,08:30,08:19,05:15,2013-01-01 05:15:00
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,5,29,2013-01-01 05:00:00,United airlines,0,05:33,08:50,08:30,05:29,2013-01-01 05:29:00
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,5,40,2013-01-01 05:00:00,American airlines,0,05:42,09:23,08:50,05:40,2013-01-01 05:40:00
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,5,45,2013-01-01 05:00:00,Jetblue airways,0,05:44,10:04,10:22,05:45,2013-01-01 05:45:00
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,6,0,2013-01-01 06:00:00,Delta airlines,0,05:54,08:12,08:37,06:00,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,...,14,55,2013-09-30 14:00:00,Endeavor airlines,1,00:00,00:00,16:34,14:55,2013-09-30 14:55:00
336772,336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,...,22,0,2013-09-30 22:00:00,Endeavor airlines,1,00:00,00:00,23:12,22:00,2013-09-30 22:00:00
336773,336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,...,12,10,2013-09-30 12:00:00,Envoy airlines,1,00:00,00:00,13:30,12:10,2013-09-30 12:10:00
336774,336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,...,11,59,2013-09-30 11:00:00,Envoy airlines,1,00:00,00:00,13:44,11:59,2013-09-30 11:59:00
336775,336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,...,8,40,2013-09-30 08:00:00,Envoy airlines,1,00:00,00:00,10:20,08:40,2013-09-30 08:40:00

In [42]:
df['dep_time'] = pd.to_datetime(df['dep_time_format'], format='%H:%M').dt.time

In [43]:
df['sched_dep_time'] = pd.to_datetime(df['sched_dep_time_formatted'], format='%H:%M').dt.time

In [44]:
df['arr_time'] = pd.to_datetime(df['arr_time_format'], format='%H:%M').dt.time

In [45]:
df['sched_arr_time'] = pd.to_datetime(df['sched_arr_time_formatted'], format='%H:%M').dt.time

In [46]:
df

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,hour,minute,time_hour,name,is_cancalled,dep_time_format,arr_time_format,sched_arr_time_formatted,sched_dep_time_formatted,flight_date
0,0,2013,1,1,05:17:00,05:15:00,2.0,08:30:00,08:19:00,11.0,...,5,15,2013-01-01 05:00:00,United airlines,0,05:17,08:30,08:19,05:15,2013-01-01 05:15:00
1,1,2013,1,1,05:33:00,05:29:00,4.0,08:50:00,08:30:00,20.0,...,5,29,2013-01-01 05:00:00,United airlines,0,05:33,08:50,08:30,05:29,2013-01-01 05:29:00
2,2,2013,1,1,05:42:00,05:40:00,2.0,09:23:00,08:50:00,33.0,...,5,40,2013-01-01 05:00:00,American airlines,0,05:42,09:23,08:50,05:40,2013-01-01 05:40:00
3,3,2013,1,1,05:44:00,05:45:00,-1.0,10:04:00,10:22:00,-18.0,...,5,45,2013-01-01 05:00:00,Jetblue airways,0,05:44,10:04,10:22,05:45,2013-01-01 05:45:00
4,4,2013,1,1,05:54:00,06:00:00,-6.0,08:12:00,08:37:00,-25.0,...,6,0,2013-01-01 06:00:00,Delta airlines,0,05:54,08:12,08:37,06:00,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,00:00:00,14:55:00,NaN,00:00:00,16:34:00,NaN,...,14,55,2013-09-30 14:00:00,Endeavor airlines,1,00:00,00:00,16:34,14:55,2013-09-30 14:55:00
336772,336772,2013,9,30,00:00:00,22:00:00,NaN,00:00:00,23:12:00,NaN,...,22,0,2013-09-30 22:00:00,Endeavor airlines,1,00:00,00:00,23:12,22:00,2013-09-30 22:00:00
336773,336773,2013,9,30,00:00:00,12:10:00,NaN,00:00:00,13:30:00,NaN,...,12,10,2013-09-30 12:00:00,Envoy airlines,1,00:00,00:00,13:30,12:10,2013-09-30 12:10:00
336774,336774,2013,9,30,00:00:00,11:59:00,NaN,00:00:00,13:44:00,NaN,...,11,59,2013-09-30 11:00:00,Envoy airlines,1,00:00,00:00,13:44,11:59,2013-09-30 11:59:00
336775,336775,2013,9,30,00:00:00,08:40:00,NaN,00:00:00,10:20:00,NaN,...,8,40,2013-09-30 08:00:00,Envoy airlines,1,00:00,00:00,10:20,08:40,2013-09-30 08:40:00

In [48]:
df.drop(columns=['dep_time_format',	'arr_time_format',	'sched_arr_time_formatted',	'sched_dep_time_formatted'],inplace=True)

In [49]:
df

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,origin,dest,air_time,distance,hour,minute,time_hour,name,is_cancalled,flight_date
0,0,2013,1,1,05:17:00,05:15:00,2.0,08:30:00,08:19:00,11.0,...,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,United airlines,0,2013-01-01 05:15:00
1,1,2013,1,1,05:33:00,05:29:00,4.0,08:50:00,08:30:00,20.0,...,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,United airlines,0,2013-01-01 05:29:00
2,2,2013,1,1,05:42:00,05:40:00,2.0,09:23:00,08:50:00,33.0,...,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,American airlines,0,2013-01-01 05:40:00
3,3,2013,1,1,05:44:00,05:45:00,-1.0,10:04:00,10:22:00,-18.0,...,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,Jetblue airways,0,2013-01-01 05:45:00
4,4,2013,1,1,05:54:00,06:00:00,-6.0,08:12:00,08:37:00,-25.0,...,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,Delta airlines,0,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,00:00:00,14:55:00,NaN,00:00:00,16:34:00,NaN,...,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00,Endeavor airlines,1,2013-09-30 14:55:00
336772,336772,2013,9,30,00:00:00,22:00:00,NaN,00:00:00,23:12:00,NaN,...,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00,Endeavor airlines,1,2013-09-30 22:00:00
336773,336773,2013,9,30,00:00:00,12:10:00,NaN,00:00:00,13:30:00,NaN,...,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00,Envoy airlines,1,2013-09-30 12:10:00
336774,336774,2013,9,30,00:00:00,11:59:00,NaN,00:00:00,13:44:00,NaN,...,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00,Envoy airlines,1,2013-09-30 11:59:00
336775,336775,2013,9,30,00:00:00,08:40:00,NaN,00:00:00,10:20:00,NaN,...,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00,Envoy airlines,1,2013-09-30 08:40:00